qmd <- "iris_chapter_copy.qmd"
file.copy("iris_chapter.qmd", qmd)

test_that("autoqmd_finalise replaces autogenerated section with default message", {
  # Run finalise with default message
  autoqmd_finalise(qmd_files = qmd)

  # Read file after finalise
  txt <- readLines(qmd)

  # ----------------------------
  # 1. Start marker present
  # ----------------------------
  start_line <- grep("AUTOGENERATED-START", txt)
  expect_true(length(start_line) == 1)

  # ----------------------------
  # 2. Default warning message inserted
  # ----------------------------
  expected_msg <- c(
    "",
    "> ⚠️ **Note:** The content below is automatically generated",
    "> during rendering. Do not edit this part manually."
  )
  expect_equal(txt[(start_line + 1):(start_line + length(expected_msg))],
               expected_msg)

  # ----------------------------
  # 3. End marker still present
  # ----------------------------
  end_line <- grep("AUTOGENERATED-END", txt)
  expect_true(end_line > start_line)
})

test_that("autoqmd_finalise replaces autogenerated section with custom message", {
  # Define a custom message
  msg <- c(
    "> ⚠️ Autogenerated content removed",
    "> Do not edit manually"
  )

  # Run finalise with custom message
  autoqmd_finalise(qmd_files = qmd, message = msg)

  txt <- readLines(qmd)
  start_line <- grep("AUTOGENERATED-START", txt)

  # Message should match exactly
  expect_equal(txt[(start_line + 1):(start_line + length(msg))], msg)
})

test_that("autoqmd_finalise removes specified child directories", {
  # Create temporary child directories with files
  dir.create("child_qmd", showWarnings = FALSE)
  file.create(file.path("child_qmd", "_qmd_dummy.qmd"))

  # Ensure directory exists
  expect_true(dir.exists("child_qmd"))

  # Run finalise removing child directory
  autoqmd_finalise(qmd_files = qmd, child_dirs_rm = "child_qmd")

  # Directory should be removed
  expect_false(dir.exists("child_qmd"))
})

test_that("autoqmd_finalise validates input arguments", {
  # qmd_files not string
  expect_error(
    autoqmd_finalise(qmd_files = 123),
    "`qmd_files` must be a path"
  )

  # qmd_files do not exist
  expect_error(
    autoqmd_finalise(qmd_files = "nonexistent.qmd"),
    "`qmd_files` must be a path"
  )

  # message not character
  expect_error(
    autoqmd_finalise(qmd_files = qmd, message = 42),
    "`message` must be a character vector"
  )
})

# Cleanup
unlink(qmd)
unlink("child_qmd", recursive = TRUE)
