qmd <- "iris_chapter_copy.qmd"
file.copy("iris_chapter.qmd", qmd)

test_that("autoqmd_prepare generates children and inserts includes correctly", {
  # Directory to store generated child QMD files
  child_dir <- "child_qmd"

  # Define input data: iris species and deterministic labels
  species <- paste("Iris", levels(iris$Species))
  labels  <- gsub("\\s", ".", tolower(species))

  # Run the wrapper: generate children and insert includes
  out <- autoqmd_prepare(
    species   = species,
    label     = labels,
    template  = "species_template.qmd",
    child_dir = child_dir,
    qmd_file  = qmd,
    freeze    = "label",
    quiet     = TRUE
  )

  # ----------------------------
  # 1. Check returned structure
  # ----------------------------
  expect_type(out, "list")
  expect_named(out, c("children", "parent", "dir"))

  # ----------------------------
  # 2. One child file per species
  # ----------------------------
  expect_length(out$children, length(species))
  expect_true(all(file.exists(out$children)))

  # ----------------------------
  # 3. Parent QMD file updated with includes
  # ----------------------------
  txt <- readLines(qmd)
  txt <- txt[txt != ""] # remove empty lines for robust comparison

  # Autogenerated markers must be present
  expect_true(any(grepl("AUTOGENERATED-START", txt)))
  expect_true(any(grepl("AUTOGENERATED-END", txt)))

  # Dependency timestamp must be present
  expect_true(any(grepl("^<!-- DEPENDENCY-MTIME:", txt)))

  # Each child file should be included exactly once
  for (f in out$children) {
    expect_true(any(grepl(paste0("\\{\\{< include ", f, " >\\}\\}"), txt)))
  }

  # ----------------------------
  # 4. Placeholders in first child file are substituted
  # ----------------------------
  content <- readLines(out$children[1])
  expect_true(any(grepl("Iris setosa", content)))
  expect_false(any(grepl("\\{\\{species\\}\\}", content)))
})

test_that("autoqmd_prepare respects page breaks when requested", {
  child_dir <- "child_qmd"
  species <- paste("Iris", levels(iris$Species))
  labels  <- gsub("\\s", ".", tolower(species))

  # Generate children and insert with page breaks
  autoqmd_prepare(
    species   = species,
    label     = labels,
    template  = "species_template.qmd",
    child_dir = child_dir,
    qmd_file  = qmd,
    page_break = "newpage",
    quiet      = TRUE
  )

  txt <- readLines(qmd)

  # There should be exactly one LaTeX page break between two includes
  expect_equal(sum(grepl("\\\\newpage", txt)), length(labels) - 1)
})

test_that("autoqmd_prepare errors if parent QMD missing markers", {
  # Create a minimal QMD file without markers
  qmd <- "bad_chapter.qmd"

  child_dir <- "child_qmd"
  species <- paste("Iris", levels(iris$Species))
  labels  <- gsub("\\s", ".", tolower(species))

  # Expect an error about missing markers
  expect_error(
    autoqmd_prepare(
      species   = species,
      label     = labels,
      template  = "species_template.qmd",
      child_dir = child_dir,
      qmd_file  = qmd,
      quiet     = TRUE
    ),
    "Markers not found in parent QMD"
  )
})

test_that("autoqmd_prepare errors if template or parent file does not exist", {
  qmd <- "nonexistent.qmd"
  child_dir <- "child_qmd"
  species <- paste("Iris", levels(iris$Species))
  labels  <- gsub("\\s", ".", tolower(species))

  # Nonexistent template
  expect_error(
    autoqmd_prepare(
      species   = species,
      label     = labels,
      template  = "no_template.qmd",
      child_dir = child_dir,
      qmd_file  = qmd,
      quiet     = TRUE
    ),
    "Template does not exist"
  )

  # Nonexistent parent QMD
  expect_error(
    autoqmd_prepare(
      species   = species,
      label     = labels,
      template  = "species_template.qmd",
      child_dir = child_dir,
      qmd_file  = "no_parent.qmd",
      quiet     = TRUE
    ),
    "Parent QMD does not exist"
  )
})

# Cleanup generated files after tests
unlink("child_qmd", recursive = TRUE)
unlink(qmd, recursive = TRUE)
