qmd <- "iris_chapter_copy.qmd"
file.copy("iris_chapter.qmd", qmd)

# QMD without markers
qmd1 <- "bad_chapter.qmd"
writeLines(c("# Title", "Some content here"), qmd1)

# QMD with start marker after end marker
qmd2 <- "bad_order.qmd"
writeLines(c(
  "line1",
  "<!-- AUTOGENERATED-END -->",
  "<!-- AUTOGENERATED-START -->",
  "line2"
), qmd2)

test_that("autoqmd_cleanup replaces section with custom message", {
  # Define custom message to insert
  msg <- c(
    "<!-- This section was autogenerated and removed after render -->",
    "Please do not edit manually."
  )

  # Run cleanup
  out <- autoqmd_cleanup(
    target_file = qmd,
    message  = msg
  )

  # ----------------------------
  # 1. Returned content matches file on disk
  # ----------------------------
  txt <- readLines(qmd)
  expect_equal(out, txt)

  # ----------------------------
  # 2. Start marker remains, message inserted after it
  # ----------------------------
  start_line <- grep("AUTOGENERATED-START", txt)
  expect_true(start_line < length(txt))
  expect_equal(txt[(start_line + 1):(start_line + length(msg))], msg)

  # ----------------------------
  # 3. End marker still present
  # ----------------------------
  end_line <- grep("AUTOGENERATED-END", txt)
  expect_true(end_line > start_line)
})

test_that("autoqmd_cleanup adds a blank line after the message", {
  msg <- "Autogenerated content removed."

  out <- autoqmd_cleanup(target_file = qmd, message = msg)

  txt <- readLines(qmd)

  start_line <- grep("AUTOGENERATED-START", txt)
  expect_equal(txt[start_line + 1], msg)
  expect_equal(txt[start_line + 2], "") # blank line
})

test_that("autoqmd_cleanup errors if markers are missing or malformed", {
  # Expect error due to missing markers
  expect_error(
    autoqmd_cleanup(target_file = qmd1, message = "msg"),
    "Markers not found or malformed"
  )

  expect_error(
    autoqmd_cleanup(target_file = qmd2, message = "msg"),
    "Markers not found or malformed"
  )
})

test_that("autoqmd_cleanup validates input arguments", {
  # target_file not a string
  expect_error(
    autoqmd_cleanup(target_file = 123, message = "msg"),
    "`target_file` must be a path"
  )

  # message not character
  expect_error(
    autoqmd_cleanup(target_file = qmd, message = 42),
    "`message` must be a character vector"
  )

  # target_file does not exist
  expect_error(
    autoqmd_cleanup(target_file = "nonexistent.qmd", message = "msg"),
    "`target_file` must be a path"
  )
})

# Cleanup generated files after tests
unlink("child_qmd", recursive = TRUE)
unlink(qmd, recursive = TRUE)
unlink(qmd1, recursive = TRUE)
unlink(qmd2, recursive = TRUE)
