qmd <- "iris_chapter_copy.qmd"
file.copy("iris_chapter.qmd", qmd)

test_that("autoqmd_insert_includes inserts child includes correctly", {
  # Create a directory for generated child QMD files
  dir.create("child_qmd", showWarnings = FALSE)

  # Create dummy child QMD files to be included
  child_files <- c(
    "child_qmd/_qmd_setosa.qmd",
    "child_qmd/_qmd_versicolor.qmd"
  )
  file.create(child_files)

  # Insert child includes into the QMD file
  out <- autoqmd_insert_includes(
    qmd_file    = qmd,
    child_files = child_files,
    template    = "_species_template.qmd",
    quiet       = TRUE
  )

  # Read the modified QMD file from disk
  txt <- readLines(qmd)

  # Helper: remove empty lines and trim whitespace
  # This avoids brittle tests caused by formatting differences
  normalize <- function(x) trimws(x[x != ""])

  # 1. The returned content should exactly match what was written to disk
  expect_equal(
    normalize(out),
    normalize(txt)
  )

  # 2. The autogenerated start and end markers must still be present
  expect_true(any(grepl("AUTOGENERATED-START", txt)))
  expect_true(any(grepl("AUTOGENERATED-END", txt)))

  # 3. A dependency timestamp should be inserted when a template is provided
  expect_true(any(grepl("^<!-- DEPENDENCY-MTIME:", txt)))

  # 4. Each child file should be included exactly once
  for (f in child_files) {
    expect_true(
      any(grepl(paste0("\\{\\{< include ", f, " >\\}\\}"), txt))
    )
  }

  # 5. Child includes must only appear inside the autogenerated block
  start <- which(grepl("AUTOGENERATED-START", txt))
  end   <- which(grepl("AUTOGENERATED-END", txt))

  expect_true(start < end)

  # Everything outside the markers must not contain include directives
  outside_block <- txt[-(start:end)]
  expect_false(any(grepl("\\{\\{< include", outside_block)))
})

test_that("autoqmd_insert_includes adds page breaks when requested", {
  # Create child QMD files
  dir.create("child_qmd", showWarnings = FALSE)
  child_files <- c(
    "child_qmd/_qmd_setosa.qmd",
    "child_qmd/_qmd_versicolor.qmd"
  )
  file.create(child_files)

  # Insert includes with LaTeX page breaks between them
  autoqmd_insert_includes(
    qmd_file    = qmd,
    child_files = child_files,
    page_break  = "newpage",
    quiet       = TRUE
  )

  txt <- readLines(qmd)

  # There should be exactly one page break between two includes
  expect_equal(sum(grepl("\\\\newpage", txt)), 1)
})

# Cleanup generated files after tests
unlink("child_qmd", recursive = TRUE)
unlink(qmd, recursive = TRUE)
