# Create child QMD files
dir.create("child_qmd", showWarnings = FALSE)
child_files <- c(
  "child_qmd/setosa.qmd",
  "child_qmd/versicolor.qmd"
)
file.create(child_files)

# ---------------------------------------------------------------------------
# CASE 1: QMD FILE
# ---------------------------------------------------------------------------
qmd <- "iris_chapter_copy.qmd"
file.copy("iris_chapter.qmd", qmd, overwrite = TRUE)

test_that("autoqmd_insert_children inserts child includes correctly", {
  # Create explicit template dependency files
  template_deps <- c(
    "R/load_data.R",
    "data/species_lookup.csv"
  )
  dir.create("R", showWarnings = FALSE)
  dir.create("data", showWarnings = FALSE)
  file.create(template_deps)

  # Insert child includes into the QMD file
  out <- autoqmd_insert_children(
    target_file   = qmd,
    child_files   = child_files,
    template      = "_species_template.qmd",
    template_deps = template_deps,
    quiet         = TRUE
  )

  # Read the modified QMD file from disk
  txt <- readLines(qmd)

  # Helper: remove empty lines and trim whitespace
  # This avoids brittle tests caused by formatting differences
  normalize <- function(x) trimws(x[x != ""])

  # 1. The returned content should exactly match what was written to disk
  expect_equal(
    normalize(out),
    normalize(txt)
  )

  # 2. The autogenerated start and end markers must still be present
  expect_true(any(grepl("AUTOGENERATED-START", txt)))
  expect_true(any(grepl("AUTOGENERATED-END", txt)))

  # 3. A dependency timestamp should be inserted
  stamp_line <- txt[grepl("^<!-- DEPENDENCY-MTIME:", txt)]
  expect_length(stamp_line, 1)

  # 4. Template and explicit dependency files must appear in the stamp (NEW)
  expect_true(grepl("_species_template\\.qmd", stamp_line))
  for (f in basename(template_deps)) {
    expect_true(grepl(f, stamp_line))
  }

  # 5. Each child file should be included exactly once
  for (f in child_files) {
    expect_true(
      any(grepl(paste0("\\{\\{< include ", f, " >\\}\\}"), txt))
    )
  }

  # 6. Child includes must only appear inside the autogenerated block
  start <- which(grepl("AUTOGENERATED-START", txt))
  end   <- which(grepl("AUTOGENERATED-END", txt))

  expect_true(start < end)

  # Everything outside the markers must not contain include directives
  outside_block <- txt[-(start:end)]
  expect_false(any(grepl("\\{\\{< include", outside_block)))

  # 7. Test verbosity
  expect_message(
    autoqmd_insert_children(
      target_file   = qmd,
      child_files   = child_files,
      template      = "_species_template.qmd",
      template_deps = template_deps
    ),
    fixed = TRUE,
    paste("Updated autogenerated block in iris_chapter_copy.qmd with 2 child",
          "includes.")
  )
})


test_that("autoqmd_insert_children adds page breaks when requested", {
  # Insert includes with LaTeX page breaks between them
  autoqmd_insert_children(
    target_file = qmd,
    child_files = child_files,
    page_break  = "newpage",
    quiet       = TRUE
  )

  txt <- readLines(qmd)

  # There should be exactly one page break between two includes
  expect_equal(sum(grepl("\\\\newpage", txt)), 1)

  # Test verbosity
  expect_message(
    autoqmd_insert_children(
      target_file = qmd,
      child_files = child_files,
      page_break  = "newpage"
    ),
    fixed = TRUE,
    paste("Updated autogenerated block in iris_chapter_copy.qmd with 2 child",
          "includes. Page breaks added: \\newpage.")
  )
})

# ---------------------------------------------------------------------------
# CASE 2: YAML FILE
# ---------------------------------------------------------------------------
yml <- "_quarto_copy.yml"
file.copy("_quarto.yml", yml, overwrite = TRUE)
yaml <- "_quarto_copy.yaml"
file.copy("_quarto.yml", yaml, overwrite = TRUE)

test_that("autoqmd_insert_children inserts child entries correctly in YML", {
  # Define labels
  child_labels <- c(
    "Iris setosa",
    "Iris versicolor"
  )

  # Insert entries into YAML
  out <- autoqmd_insert_children(
    target_file  = yml,
    child_files  = child_files,
    child_labels = child_labels,
    start_marker = "# AUTOGENERATED-START",
    end_marker   = "# AUTOGENERATED-END",
    quiet        = TRUE
  )

  # Read modified file
  txt <- readLines(yml)

  # Helper: normalize whitespace and remove empty lines
  normalize <- function(x) trimws(x[x != ""])

  # 1. Returned content should match file content
  output <- normalize(out)
  names(output) <- NULL
  expect_equal(output, normalize(txt))

  # 2. Markers must still be present
  expect_true(any(grepl("AUTOGENERATED-START", txt)))
  expect_true(any(grepl("AUTOGENERATED-END", txt)))

  # 3. Each label should appear exactly once
  for (label in child_labels) {
    expect_true(any(grepl(paste0("text: ", label), txt, fixed = TRUE)))
  }

  # 4. Each child file should appear exactly once
  for (f in child_files) {
    expect_true(any(grepl(paste0("file: ", f), txt, fixed = TRUE)))
  }

  # 5. Entries must appear only within the autogenerated block
  start <- which(grepl("AUTOGENERATED-START", txt))
  end   <- which(grepl("AUTOGENERATED-END", txt))
  expect_true(start < end)

  outside_block <- txt[-(start:end)]
  expect_false(any(grepl("file:", outside_block)))

  # 6. Test verbosity
  expect_message(
    autoqmd_insert_children(
      target_file  = yml,
      child_files  = child_files,
      child_labels = child_labels,
      start_marker = "# AUTOGENERATED-START",
      end_marker   = "# AUTOGENERATED-END"
    ),
    fixed = TRUE,
    "Updated autogenerated block in _quarto_copy.yml with 2 sidebar entries."
  )
})

test_that("autoqmd_insert_children inserts child entries correctly in YAML", {
  # Define labels
  child_labels <- c(
    "Iris setosa",
    "Iris versicolor"
  )

  # Insert entries into YAML
  out <- autoqmd_insert_children(
    target_file  = yaml,
    child_files  = child_files,
    child_labels = child_labels,
    start_marker = "# AUTOGENERATED-START",
    end_marker   = "# AUTOGENERATED-END",
    quiet        = TRUE
  )

  # Read modified file
  txt <- readLines(yaml)

  # Helper: normalize whitespace and remove empty lines
  normalize <- function(x) trimws(x[x != ""])

  # 1. Returned content should match file content
  output <- normalize(out)
  names(output) <- NULL
  expect_equal(output, normalize(txt))

  # 2. Markers must still be present
  expect_true(any(grepl("AUTOGENERATED-START", txt)))
  expect_true(any(grepl("AUTOGENERATED-END", txt)))

  # 3. Each label should appear exactly once
  for (label in child_labels) {
    expect_true(any(grepl(paste0("text: ", label), txt, fixed = TRUE)))
  }

  # 4. Each child file should appear exactly once
  for (f in child_files) {
    expect_true(any(grepl(paste0("file: ", f), txt, fixed = TRUE)))
  }

  # 5. Entries must appear only within the autogenerated block
  start <- which(grepl("AUTOGENERATED-START", txt))
  end   <- which(grepl("AUTOGENERATED-END", txt))
  expect_true(start < end)

  outside_block <- txt[-(start:end)]
  expect_false(any(grepl("file:", outside_block)))

  # 6. Test verbosity
  expect_message(
    autoqmd_insert_children(
      target_file  = yaml,
      child_files  = child_files,
      child_labels = child_labels,
      start_marker = "# AUTOGENERATED-START",
      end_marker   = "# AUTOGENERATED-END"
    ),
    fixed = TRUE,
    "Updated autogenerated block in _quarto_copy.yaml with 2 sidebar entries."
  )
})

test_that("autoqmd_insert_children derives labels automatically in YML", {
  # Insert without specifying labels
  autoqmd_insert_children(
    target_file  = yml,
    child_files  = child_files,
    start_marker = "# AUTOGENERATED-START",
    end_marker   = "# AUTOGENERATED-END",
    quiet        = TRUE
  )

  txt <- readLines(yml)

  # Expected labels derived from filenames
  expected_labels <- tools::file_path_sans_ext(basename(child_files))

  for (label in expected_labels) {
    expect_true(any(grepl(paste0("text: ", label), txt, fixed = TRUE)))
  }
})

test_that("autoqmd_insert_children preserves indentation in YML", {
  # Insert without specifying labels
  autoqmd_insert_children(
    target_file  = yml,
    child_files  = child_files,
    start_marker = "# AUTOGENERATED-START",
    end_marker   = "# AUTOGENERATED-END",
    quiet        = TRUE
  )

  txt <- readLines(yml)

  # Extract inserted line
  inserted_line <- txt[grepl("text:", txt)]

  # Expect proper indentation (10 spaces before "- text")
  expect_true(all(grepl("^\\s+- text:", inserted_line)))
})

# ---------------------------------------------------------------------------
# Test errors
# ---------------------------------------------------------------------------
test_that("autoqmd_insert_children errors on malformed markers in QMD", {
  # Create a malformed QMD template (missing end marker)
  qmd <- "malformed_template.qmd"
  writeLines(
    c(
      "# Test Document",
      "",
      "<!-- AUTOGENERATED-START -->",
      "Some content without an end marker"
    ),
    qmd
  )

  # Expect an error due to malformed markers
  expect_error(
    autoqmd_insert_children(
      target_file = qmd,
      child_files = child_files,
      quiet = TRUE
    ),
    "Markers not found or malformed"
  )

  # Cleanup
  unlink(qmd)
})


test_that("autoqmd_insert_children errors on reversed markers in QMD", {
  # Create a malformed QMD template (switch markers)
  qmd <- "reversed_template.qmd"
  writeLines(
    c(
      "# Test Document",
      "",
      "<!-- AUTOGENERATED-END -->",
      "Content",
      "<!-- AUTOGENERATED-START -->"
    ),
    qmd
  )

  # Expect an error due to malformed markers
  expect_error(
    autoqmd_insert_children(
      target_file = qmd,
      child_files = child_files,
      quiet = TRUE
    ),
    "Markers not found or malformed"
  )

  # Cleanup
  unlink(qmd)
})


test_that("autoqmd_insert_children errors on malformed markers in YML", {
  # Create a malformed YML template (missing end marker)
  yml <- "_quarto_malformed.yml"
  writeLines(
    c(
      "website:",
      "  sidebar:",
      "    contents:",
      "      - section: \"Iris\"",
      "        contents:",
      "          # AUTOGENERATED-START"
    ),
    yml
  )

  # Expect an error due to malformed markers
  expect_error(
    autoqmd_insert_children(
      target_file = yml,
      child_files = child_files,
      start_marker = "# AUTOGENERATED-START",
      end_marker   = "# AUTOGENERATED-END",
      quiet = TRUE
    ),
    "Markers not found or malformed"
  )

  # Cleanup
  unlink(yml)
})


test_that("autoqmd_insert_children errors on duplicated markers in YML", {
  # Create YAML template with duplicated start markers
  yml <- "_quarto_reversed.yml"
  writeLines(
    c(
      "website:",
      "  sidebar:",
      "    contents:",
      "      - section: \"Iris\"",
      "        contents:",
      "          # AUTOGENERATED-START",
      "          # AUTOGENERATED-START",
      "          # AUTOGENERATED-END"
    ),
    yml
  )

  # Expect an error due to malformed markers
  expect_error(
    autoqmd_insert_children(
      target_file = yml,
      child_files = child_files,
      start_marker = "# AUTOGENERATED-START",
      end_marker   = "# AUTOGENERATED-END",
      quiet = TRUE
    ),
    "Markers not found or malformed"
  )

  # Cleanup
  unlink(yml)
})

test_that("autoqmd_insert_children errors on wrong file type", {
  # Create a txt template
  txt <- "template.txt"
  writeLines(
    c(
      "# Test Document",
      "",
      "<!-- AUTOGENERATED-START -->",
      "<!-- AUTOGENERATED-END -->"
    ),
    txt
  )

  # Expect an error due to malformed markers
  expect_error(
    autoqmd_insert_children(
      target_file = txt,
      child_files = child_files,
      quiet = TRUE
    ),
    "Unsupported file type"
  )

  # Cleanup
  unlink(txt)
})

# Cleanup generated files after tests
unlink("child_qmd", recursive = TRUE)
unlink("R", recursive = TRUE)
unlink("data", recursive = TRUE)
unlink(qmd)
unlink(yml)
unlink(yaml)
