#' Replace autogenerated section in a QMD file with a custom message
#'
#' This function post-processes a Quarto (`.qmd`) file by replacing the
#' section between specified start and end markers with a custom message. It is
#' useful for ensuring that autogenerated content is clearly marked and
#' preventing manual edits in those sections.
#'
#' @param qmd_file Character string. Path to the QMD file to modify.
#' @param message Character vector. The message to insert between the start
#' and end markers. Each element of the vector is written as a separate line.
#' @param start_marker Character string. The marker indicating where the
#' autogenerated section starts. Defaults to
#' `"<!-- AUTOGENERATED-START -->"`.
#' @param end_marker Character string. The marker indicating where the
#' autogenerated section ends. Defaults to `"<!-- AUTOGENERATED-END -->"`.
#'
#' @details
#' The function searches for the lines matching `start_marker` and
#' `end_marker`, and replaces all content between them (inclusive of the
#' start marker but excluding the end marker) with the text supplied in
#' `message`.
#'
#' A blank line is added after the message for readability.
#' If the markers are missing or appear in the wrong order, the function
#' stops with an error.
#'
#' This function is commonly used together with
#' [`autoqmd_generate_children()`] and [`autoqmd_insert_includes()`]
#' in a Quarto pre-/post-render workflow.
#'
#' @return Invisibly returns the modified lines as a character vector.
#'   The QMD file is also overwritten on disk.
#'
#' @seealso [autoqmd_generate_children()], [autoqmd_insert_includes()],
#'   [autoqmd_finalise()]
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Replace autogenerated block after rendering
#' autoqmd_cleanup(
#'   qmd_file = "report.qmd",
#'   message = c(
#'     "<!-- This section was autogenerated and removed after render -->"
#'   )
#' )
#' }
autoqmd_cleanup <- function(
  qmd_file,
  message,
  start_marker = "<!-- AUTOGENERATED-START -->",
  end_marker   = "<!-- AUTOGENERATED-END -->"
) {
  # Read the file contents
  lines <- readLines(qmd_file)

  # Find markers
  start <- grep(start_marker, lines)
  end   <- grep(end_marker, lines)
  if (length(start) != 1 || length(end) != 1 || start > end) {
    stop("Markers not found or malformed in QMD file: ", qmd_file)
  }

  # Construct updated file content:
  # - Keep everything up to the start marker
  # - Insert the warning message
  # - Keep everything from the end marker onward
  lines_new <- c(
    lines[1:start],
    message,
    "",
    lines[end:length(lines)]
  )

  # Write modified lines back to file
  writeLines(lines_new, qmd_file)

  invisible(lines_new)
}
