#' Insert autogenerated child documents into Quarto files
#'
#' This function inserts references to autogenerated child documents into a
#' Quarto file. It supports both `.qmd` documents and Quarto configuration
#' files (`.yml` or `.yaml`), adapting its behavior to the file type.
#'
#' For `.qmd` files, the function replaces the lines between
#' `<!-- AUTOGENERATED-START -->` and `<!-- AUTOGENERATED-END -->`
#' with Quarto include directives of the form
#' `{{< include path >}}`. Optionally, LaTeX page breaks
#' (`\\newpage` or `\\clearpage`) can be inserted between includes.
#'
#' For Quarto configuration files such as `_quarto.yml`, the function replaces
#' the lines between marker comments with YAML entries referencing the child
#' documents. These entries can be used, for example, in website sidebars or
#' navigation menus.
#'
#' Marker syntax must match the file type:
#' \itemize{
#'   \item `.qmd` files: `<!-- AUTOGENERATED-START -->` and
#'         `<!-- AUTOGENERATED-END -->`
#'   \item `.yml` or `.yaml` files: `# AUTOGENERATED-START` and
#'         `# AUTOGENERATED-END`
#' }
#'
#' @param target_file Path to the Quarto file to modify. Supported file types
#'   are `.qmd`, `.yml`, and `.yaml`.
#' @param child_files Character vector of file paths to include.
#' @param child_labels Optional character vector of labels corresponding to
#'   `child_files`. These are used in YAML outputs (e.g., Quarto website
#'   sidebars). If `NULL`, labels are derived from the filenames.
#' @param start_marker Marker string indicating the start of the autogenerated
#'   block. Defaults to `"<!-- AUTOGENERATED-START -->"`.
#' @param end_marker Marker string indicating the end of the autogenerated
#'   block. Defaults to `"<!-- AUTOGENERATED-END -->"`.
#' @param page_break Character string specifying a LaTeX page break to
#'   insert between includes. Options: `"newpage"`, `"clearpage"`.
#'   Defaults to `NULL` (no page breaks).
#' @param template Optional path to the QMD template used to generate
#'   the child files. Its modification time will be
#'   tracked.
#' @param template_deps Optional character vector of file paths that are
#'   explicit dependencies of the template (e.g. R scripts, data files).
#'   Their modification times are included in the dependency stamp.
#' @param quiet Logical; if `TRUE`, suppresses messages.
#'
#' @details
#' For `.qmd` files, dependency timestamps derived from `template` and
#' `template_deps` are embedded as invisible HTML comments via
#' [autoqmd_dependency_stamp()]. This ensures that Quarto's `freeze:` mechanism
#' correctly detects when templates or dependencies have changed.
#'
#' @return Invisibly returns the modified lines of the target file.
#'   The file is updated on disk.
#'
#' @seealso [autoqmd_generate_children()], [autoqmd_dependency_stamp()],
#' [autoqmd_prepare()]
#'
#' @export
#'
#' @importFrom assertthat is.string is.flag
#' @importFrom tools file_ext file_path_sans_ext
#'
#' @examples
#' \dontrun{
#' my_species <- paste("Iris", levels(iris$Species))
#'
#' # Create child document for each species
#' # Use freeze to keep child files with label names
#' out_files <- autoqmd_generate_children(
#'   species = my_species,
#'   label = gsub("\\s", ".", tolower(my_species)),
#'   template = "_species_template.qmd",
#'   child_dir = "child_qmd",
#'   freeze = "label"
#' )
#'
#' # Include child files in report with page breaks
#' autoqmd_insert_includes(
#'   target_file = "report.qmd",
#'   child_files = out_files,
#'   template = "_species_template.qmd",
#'   template_deps = c("R/load_species_data.R", "data/species_lookup.csv"),
#'   page_break = "newpage"
#' )
#' }
autoqmd_insert_includes <- function(
  target_file,
  child_files,
  child_labels = NULL,
  start_marker = "<!-- AUTOGENERATED-START -->",
  end_marker = "<!-- AUTOGENERATED-END -->",
  page_break = NULL,
  template = NULL,
  template_deps = NULL,
  quiet = FALSE
) {
  # Validation
  stopifnot("`target_file` must be a path to a Quarto file to modify." =
              assertthat::is.string(target_file))
  stopifnot("`target_file` must be a path to a Quarto file to modify." =
              file.exists(target_file))
  stopifnot("`child_files` must be a path to child files to include." =
              all(sapply(child_files, assertthat::is.string)))
  stopifnot("`child_files` must be a path to child files to include." =
              all(sapply(child_files, file.exists)))
  stopifnot("`start_marker` must be a scalar character vector." =
              is.string(start_marker))
  stopifnot("`end_marker` must be a scalar character vector." =
              assertthat::is.string(end_marker))
  stopifnot(
    "page_break must be NULL, 'newpage', or 'clearpage'." =
      is.null(page_break) || page_break %in% c("newpage", "clearpage")
  )
  stopifnot(
    "`template_deps` must be NULL or a character vector of file paths." =
      is.null(template_deps) ||
      (all(sapply(template_deps, assertthat::is.string)) &&
       all(sapply(template_deps, file.exists)))
  )
  stopifnot("`quiet` must be a scalar logical vector." =
              assertthat::is.flag(quiet))

  # Get file extension
  ext <- tolower(tools::file_ext(target_file))

  # ---------------------------------------------------------------------------
  # CASE 1: QMD FILE
  # ---------------------------------------------------------------------------
  if (ext == "qmd") {
    # Read file
    lines <- readLines(target_file)

    # Find markers
    start <- grep(start_marker, lines)
    end   <- grep(end_marker, lines)
    if (length(start) != 1 || length(end) != 1 || start > end) {
      stop("Markers not found or malformed in QMD file: ", target_file)
    }

    # Generate dependency timestamps using the helper
    timestamp_line <- autoqmd_dependency_stamp(c(template, template_deps))

    # Build child includes
    if (!is.null(page_break)) {
      # Insert page break between includes, but not after the last one
      include_lines <- paste0("{{< include ", child_files, " >}}")
      child_lines <- paste(
        paste(include_lines, collapse = paste0("\n\n\\", page_break, "\n\n")),
        "\n"
      )
    } else {
      child_lines <- sprintf("{{< include %s >}}\n", child_files)
    }

    # Combine the hidden timestamp and includes
    autogenerated_block <- c(timestamp_line, "", child_lines)

    # Replace block between markers
    lines_new <- c(
      lines[1:start],
      "",
      autogenerated_block,
      lines[end:length(lines)]
    )

    # Write back to file
    writeLines(lines_new, target_file)

    if (!quiet) {
      msg <- paste0("Updated autogenerated block in ", target_file,
                    " with ", length(child_files), " child includes.")
      if (!is.null(page_break)) {
        msg <- paste0(msg, " Page breaks added: \\", page_break, ".")
      }
      message(msg)
    }

    return(invisible(lines_new))
  }

  # ---------------------------------------------------------------------------
  # CASE 2: YAML FILE (_quarto.yml)
  # ---------------------------------------------------------------------------
  if (ext %in% c("yml", "yaml")) {
    # Read file
    lines <- readLines(target_file)

    # Find markers
    start <- grep(start_marker, lines)
    end   <- grep(end_marker, lines)
    if (length(start) != 1 || length(end) != 1 || start > end) {
      stop(
        "Markers not found or malformed in YAML file: ", target_file,
        ". Use YAML comments such as '# AUTOGENERATED-START'."
      )
    }

    # Validate labels
    if (!is.null(child_labels)) {
      stopifnot("`child_labels` must be character." =
                  all(sapply(child_labels, assertthat::is.string)))
      stopifnot("`child_labels` must match `child_files` in length." =
                  length(child_labels) == length(child_files))
    } else {
      child_labels <- tools::file_path_sans_ext(basename(child_files))
    }

    # Determine indentation from the start marker
    indent <- sub("^(\\s*).*", "\\1", lines[start])
    indent_item <- paste0(indent, "  ")
    indent_field <- paste0(indent_item, "  ")

    # Convert paths to use forward slashes
    rel_paths <- gsub("\\\\", "/", child_files)

    # Build YAML sidebar entries
    yaml_entries <- unlist(
      Map(function(label, path) {
        c(
          paste0(indent_item, "- text: ", label),
          paste0(indent_field, "file: ", path)
        )
      }, child_labels, rel_paths)
    )

    # Replace block between markers
    lines_new <- c(
      lines[1:start],
      yaml_entries,
      lines[end:length(lines)]
    )

    writeLines(lines_new, target_file)

    if (!quiet) {
      message(
        "Updated autogenerated block in ", target_file,
        " with ", length(child_files), " sidebar entries."
      )
    }

    return(invisible(lines_new))
  }

  stop(
    "Unsupported file type: ", target_file,
    ". Only '.qmd', '.yml', and '.yaml' are supported."
  )
}
